version: '3.8'

services:  
  db:
    image: mysql:latest
    environment:
      - MYSQL_USER=epytodo
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=epytodo
      - MYSQL_ROOT_PASSWORD=password

    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/postgresql/db
      - ./epytodo.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

volumes:
  db-data: